[tool.poetry]
name = "tictactoe"
version = "0.1.0"
description = ""
authors = ["braulioblake"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
display = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
